### ISSUE TITLE
Rows parameter and 500 Server Errors

### ISSUE THREAD

**Issue by andycasey** [andycasey/ads#13]
Peter Weilbacher (AIP) reports:

> I noticed that your example script
> https://github.com/andycasey/ads/blob/master/examples/monthly-institute- publications/stromlo_publications.py
> does not run. I get

> $ python stromlo_publications.py
> There were 20 articles found. Sorting and downloading..
> Traceback (most recent call last):
>   File "stromlo_publications.py", line 50, in <module>
>     [ads.retrieve_article(article, output_filename=article.bibcode + ".pdf") for article in sorted_articles]
>   File "/home/pmw/.local/lib/python2.7/site-packages/ads/core.py", line 535, in retrieve_article
>     arxiv_r.raise_for_status()
>   File "/home/pmw/.local/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error

And mentions the `rows` parameter is not behaving as expected. This may be due to a bug that has arisen in my code, or it may be due to the rollout of the new ADS API (which is expected around now..)

**Comment by andycasey** [comment]
The `retrieve_article` function would try and download the paper through the "Full Online article (PDF)" link on ADS, and revert to arXiv in case the user did not have access to the library. The URLs for the full article and arXiv link were both accessed via the ADS web page.

ADS appears to have updated their server behaviour, which has caused this functionality to break on the full article and arxiv links.

I have posted a query on this at https://groups.google.com/forum/#!topic/adsabs-dev-api/E4HZ55rnnTo
