### ISSUE TITLE
Connection error when building citation tree

### ISSUE THREAD

**Issue by willettk** [andycasey/ads#15]
7d5dca1130b197579eba9108715fcb8d1669b3ec from the examples fails in building a citation tree. Output below:

```
[willettk@x-131-212-237-196 citation-tree]$ python citation_tree.py 
Traceback (most recent call last):
  File "citation_tree.py", line 13, in <module>
    paper.build_citation_tree(depth=2)
  File "//anaconda/lib/python2.7/site-packages/ads/core.py", line 294, in build_citation_tree
    bibcode=article.bibcode), **kwargs) for article in level]
  File "//anaconda/lib/python2.7/site-packages/ads/core.py", line 405, in search
    return query(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/ads/core.py", line 340, in __init__
    r = requests.get(ADS_HOST + "/search/", params=metadata_payload)
  File "//anaconda/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "//anaconda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))
```

**Comment by jonnybazookatone** [comment]
Can we change the title of this issue, or close and open a new one for `build_citation_tree` and `build_reference_tree` (to remove any possible confusion of people opening tickets in the future)? As, if I'm not mistaken, the initial error given above is from the old ADS API, and not relevant to the changes made on this client, as there is no implementation of `build_citation_tree` and `build_reference_tree` yet.

**Comment by jonnybazookatone** [comment]
@andycasey I'll close this for now, re-open if you didn't like my above suggestion.
